font=Cantarell 11
background-color=#eff1f5ff
text-color=#4c4f69ff
border-color=#1e66f5ff
border-size=2
border-radius=10
default-timeout=5000
width=360
height=120
margin=12
padding=12

[urgency=critical]
border-color=#d20f39ff
default-timeout=0
format=<b>Critical:</b> %s\n%b
